apiVersion: apps/v1
kind: Deployment
metadata:
 name: voting-app
 labels:
      app: voting-app
      type: demo-voting-app
spec:
 template:
  metadata:
    name: voting-app
    labels:
      app: voting-app
      type: demo-voting-app
  spec:
    containers:
      - name: voting-app
        image: kodekloud/examplevotingapp_vote:v1
 replicas: 2
 selector:
    matchLabels:
        app: voting-app
        type: demo-voting-app
