apiVersion: v1
kind: Pod
metadata:
  name: db 
  labels:
    app: db
    type: back-end
spec:
  containers:
  - name: db
    image: postgres:latest
    env: 
     - name: POSTGRES_HOST_AUTH_METHOD
       value: trust
