#YAML is Case Sensitive
#space and identation is importante in YAML
#Key:Value Pair
---
"apple" : "The fruit is red"
1 : "aaa's roll number.."

#lists
---
- apple #and Apple is not the same
- mango
- banana
- Apple

#dictionary
---
cities:
  - aaa
  - bbb
  - ccc

#abbreviated format for list
---
cities: [" pinas","aaa","bbb"]

#abbreviated format for dictionary
---
student: {name: "egg", age: "2", gender: "male"}
...