apiVersion: apps/v1
kind: Deployment
metadata:
 name: db
 labels:
      app: db
      type: demo-voting-app
spec:
 template:
  metadata:
    name: db
    labels:
      app: db
      type: demo-voting-app
  spec:
    containers:
      - name: db
        image: postgres
        env: 
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
 replicas: 2
 selector:
    matchLabels:
        app: db
        type: demo-voting-app