apiVersion: v1
kind: Service
metadata:
    name: result-app
spec:

    type: NodePort
    ports:
     - targetPort: 80 
       port: 80
    selector:
       app: result-app
       type: demo-voting-app 
