apiVersion: v1
kind: Service
metadata:
    name: voting-app
spec:

    type: NodePort
    ports:
     - targetPort: 80 
       port: 80 
    selector:
       app: voting-app
       type: demo-voting-app
