apiVersion: apps/v1
kind: Deployment
metadata:
 name: worker-app
 labels:
      app: worker-app
      type: demo-voting-app
spec:
 template:
  metadata:
    name: worker-app
    labels:
      app: worker-app
      type: demo-voting-app
  spec:
    containers:
    - name: worker
      image: kodekloud/examplevotingapp_worker:v1
 replicas: 1 
 selector:
    matchLabels:
        app: worker-app
        type: demo-voting-app
